version: 2
jobs:
  build:
    machine:
      docker:
        image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: build
          destination: tech-tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build